--------------------------------------------------------
--  File created - èetvrtak-prosinca-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table D_COMPANY_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_COMPANY_SETTINGS" 
   (	"COMPANY" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(4000 BYTE), 
	"VALUE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" 
 LOB ("VALUE") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_COMPANY_SETTINGS" TO "APP_PORTAL";
--------------------------------------------------------
--  DDL for Table D_ENTITIES
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_ENTITIES" 
   (	"ID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
  GRANT REFERENCES ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_UTIL";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITIES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITIES" TO "KONDOR";
--------------------------------------------------------
--  DDL for Table D_ENTITY_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" 
   (	"ENTITY" VARCHAR2(200 BYTE), 
	"MODULE" VARCHAR2(200 BYTE), 
	"PURPOSE" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"VALUE" CLOB, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" 
 LOB ("VALUE") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_UTIL";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "KONDOR";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "APP_CUST_MENU";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "APP_CUST_MENU2";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" TO "APP_CUST_MENU_02";
--------------------------------------------------------
--  DDL for Table D_ENTITY_TYPES
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_ENTITY_TYPES" 
   (	"TAG" VARCHAR2(3 BYTE), 
	"TYPE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ENTITY_TYPES" TO "KONDOR";
--------------------------------------------------------
--  DDL for Table D_ENVIRONMENTS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_ENVIRONMENTS" 
   (	"ENVIRONMENT" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ORDR" NUMBER, 
	"DISCLOSED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Table D_MAILING_LIST_USERS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_MAILING_LIST_USERS" 
   (	"NAME" VARCHAR2(200 BYTE), 
	"USERNAME" VARCHAR2(200 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_UTIL";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_LOG";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LIST_USERS" TO "KONDOR";
--------------------------------------------------------
--  DDL for Table D_MAILING_LISTS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_MAILING_LISTS" 
   (	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_UTIL";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_LOG";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_MAILING_LISTS" TO "KONDOR";
--------------------------------------------------------
--  DDL for Table D_ROLES
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_ROLES" 
   (	"ROLE" VARCHAR2(100 BYTE), 
	"ENTITY" VARCHAR2(100 BYTE), 
	"ROLE_LEVEL" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_ROLES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ROLES" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ROLES" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ROLES" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ROLES" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ROLES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ROLES" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ROLES" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ROLES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ROLES" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ROLES" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ROLES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_ROLES" TO "KONDOR";
  GRANT SELECT ON "AP_APPLICATIONS"."D_ROLES" TO "APP_PORTAL";
--------------------------------------------------------
--  DDL for Table D_SERVERS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_SERVERS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"HOSTNAME" VARCHAR2(255 BYTE), 
	"IP_ADDRESS" VARCHAR2(255 BYTE), 
	"OPERATING_SYSTEM" VARCHAR2(255 BYTE), 
	"MEMORY_SIZE_GB" NUMBER, 
	"LOCATION" VARCHAR2(255 BYTE), 
	"IS_ACTIVE" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"OWNER" VARCHAR2(255 BYTE), 
	"AGREEMENT_PERSON" VARCHAR2(255 BYTE), 
	"RISK" VARCHAR2(255 BYTE), 
	"ENVIRONMENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Table D_SOFTWARE
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_SOFTWARE" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"VERSION" VARCHAR2(255 BYTE), 
	"SOFTWARE_TYPE_NAME" VARCHAR2(255 BYTE), 
	"SECURITY_TYPE" VARCHAR2(255 BYTE), 
	"VERSION_CONTROL_SYSTEM_URL" VARCHAR2(4000 BYTE), 
	"INSTRUCTIONS_URL" VARCHAR2(4000 BYTE), 
	"TECHNOLOGIES" VARCHAR2(4000 BYTE), 
	"DEVELOPMENT_TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Table D_SOFTWARE_DETAILS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SOFTWARE_ID" NUMBER, 
	"URLS" CLOB, 
	"STATUS" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"RISK" VARCHAR2(255 BYTE), 
	"OWNER" VARCHAR2(255 BYTE), 
	"MAINTAINER" VARCHAR2(255 BYTE), 
	"SERVER_ID" NUMBER, 
	"PARENT_ID" NUMBER, 
	"PRIMARY" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" 
 LOB ("URLS") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table D_SOFTWARE_TYPES
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_SOFTWARE_TYPES" 
   (	"SOFTWARE_TYPE_NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ORDR" NUMBER, 
	"DISCLOSED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Table D_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_USER_ROLES" 
   (	"USERNAME" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(100 BYTE) DEFAULT 'ACTIVE', 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE), 
	"ENTITY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "KONDOR";
  GRANT ALTER ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT INDEX ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT REFERENCES ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT READ ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT ON COMMIT REFRESH ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT QUERY REWRITE ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT DEBUG ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
  GRANT FLASHBACK ON "AP_APPLICATIONS"."D_USER_ROLES" TO "APP_PORTAL";
--------------------------------------------------------
--  DDL for Table D_USER_STATUS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_USER_STATUS" 
   (	"STATUS" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_UTIL";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_LOG";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "KONDOR";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USER_STATUS" TO "APP_PORTAL";
--------------------------------------------------------
--  DDL for Table D_USERS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."D_USERS" 
   (	"USERNAME" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(200 BYTE), 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(500 BYTE), 
	"COMPANY" VARCHAR2(200 BYTE) DEFAULT 'KONZUM', 
	"STATUS" VARCHAR2(100 BYTE) DEFAULT 'ACTIVE', 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER, 
	"THEME" VARCHAR2(100 BYTE) DEFAULT 'dark', 
	"IMAGE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT REFERENCES ON "AP_APPLICATIONS"."D_USERS" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USERS" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USERS" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USERS" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USERS" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USERS" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USERS" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USERS" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USERS" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USERS" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USERS" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USERS" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USERS" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USERS" TO "KONDOR";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USERS" TO "APP_SUPRISK";
  GRANT ALTER ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT DELETE ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT INDEX ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT INSERT ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT SELECT ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT UPDATE ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT REFERENCES ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT READ ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT ON COMMIT REFRESH ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT QUERY REWRITE ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT DEBUG ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
  GRANT FLASHBACK ON "AP_APPLICATIONS"."D_USERS" TO "APP_PORTAL";
--------------------------------------------------------
--  DDL for Table MPC_LIST
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."MPC_LIST" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(200 BYTE), 
	"LOGIN_TYPE" VARCHAR2(10 BYTE), 
	"EMPLOYEE_ID" VARCHAR2(20 BYTE), 
	"MPC_ID" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"ORGANIZATION" VARCHAR2(20 BYTE), 
	"OIB" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Table PS_TXN
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."PS_TXN" 
   (	"ID" NUMBER(20,0), 
	"PARENTID" NUMBER(20,0), 
	"COLLID" NUMBER(10,0), 
	"CONTENT" BLOB, 
	"CREATION_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SECRET_SANTA
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."SECRET_SANTA" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"YEAR_OF_BIRTH" NUMBER, 
	"ROOM_NUMBER" NUMBER, 
	"INTERESTS" VARCHAR2(4000 BYTE), 
	"ID_MATCHED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Table SQL_SUBPROGRAMS
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."SQL_SUBPROGRAMS" 
   (	"OBJECT_NAME_PARENT" VARCHAR2(100 BYTE), 
	"VERSION" VARCHAR2(100 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"OBJECT_TYPE" VARCHAR2(100 BYTE), 
	"LINES" NUMBER, 
	"OBJECT_TYPE_PARENT" VARCHAR2(100 BYTE), 
	"OWNER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Table SQL_VERSION
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."SQL_VERSION" 
   (	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"OBJECT_TYPE" VARCHAR2(100 BYTE), 
	"SOURCE" CLOB, 
	"VERSION" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"ACTIVE" VARCHAR2(10 BYTE), 
	"CREATE_BY" VARCHAR2(100 BYTE) DEFAULT USER, 
	"CREATE_DT" DATE, 
	"OWNER" VARCHAR2(100 BYTE), 
	"OSUSER" VARCHAR2(200 BYTE), 
	"SVN_VERSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" 
 LOB ("SOURCE") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_MAILING
--------------------------------------------------------

  CREATE TABLE "AP_APPLICATIONS"."T_MAILING" 
   (	"ID" NUMBER, 
	"SUBJECT" VARCHAR2(400 BYTE), 
	"BODY" CLOB, 
	"ATTACHMENT" CLOB, 
	"SENT" VARCHAR2(1 BYTE), 
	"NOT_BEFORE" DATE, 
	"MAILING_LIST" VARCHAR2(200 BYTE), 
	"MAIL_TYPE" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(100 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" 
 LOB ("BODY") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTACHMENT") STORE AS SECUREFILE (
  TABLESPACE "TBS_UTIL_APP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "AP_APPLICATIONS"."T_MAILING" TO "AP_MASTER";
  GRANT UPDATE ON "AP_APPLICATIONS"."T_MAILING" TO "AP_MASTER";
  GRANT DELETE ON "AP_APPLICATIONS"."T_MAILING" TO "AP_MASTER";
  GRANT INSERT ON "AP_APPLICATIONS"."T_MAILING" TO "AP_MASTER";
  GRANT SELECT ON "AP_APPLICATIONS"."T_MAILING" TO "AP_UTIL";
  GRANT UPDATE ON "AP_APPLICATIONS"."T_MAILING" TO "AP_UTIL";
  GRANT DELETE ON "AP_APPLICATIONS"."T_MAILING" TO "AP_UTIL";
  GRANT INSERT ON "AP_APPLICATIONS"."T_MAILING" TO "AP_UTIL";
  GRANT SELECT ON "AP_APPLICATIONS"."T_MAILING" TO "AP_LOG";
  GRANT UPDATE ON "AP_APPLICATIONS"."T_MAILING" TO "AP_LOG";
  GRANT DELETE ON "AP_APPLICATIONS"."T_MAILING" TO "AP_LOG";
  GRANT INSERT ON "AP_APPLICATIONS"."T_MAILING" TO "AP_LOG";
  GRANT SELECT ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR_APP";
  GRANT UPDATE ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR_APP";
  GRANT DELETE ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR_APP";
  GRANT INSERT ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR_APP";
  GRANT SELECT ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR";
  GRANT UPDATE ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR";
  GRANT DELETE ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR";
  GRANT INSERT ON "AP_APPLICATIONS"."T_MAILING" TO "KONDOR";
--------------------------------------------------------
--  DDL for Index D_COMPANY_SETTINGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_COMPANY_SETTINGS_PK" ON "AP_APPLICATIONS"."D_COMPANY_SETTINGS" ("COMPANY", "TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 166 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_ENTITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_ENTITIES_PK" ON "AP_APPLICATIONS"."D_ENTITIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_ENTITIES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_ENTITIES_UK1" ON "AP_APPLICATIONS"."D_ENTITIES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_ENTITY_ATTRIBUTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES_PK" ON "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" ("ENTITY", "NAME", "MODULE", "PURPOSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_ENTITY_TYPE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_ENTITY_TYPE_PK1" ON "AP_APPLICATIONS"."D_ENTITY_TYPES" ("TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SYS_C0024664
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SYS_C0024664" ON "AP_APPLICATIONS"."D_ENVIRONMENTS" ("ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_MAILING_LISTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_MAILING_LISTS_PK" ON "AP_APPLICATIONS"."D_MAILING_LISTS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_ROLES_PK" ON "AP_APPLICATIONS"."D_ROLES" ("ROLE", "ENTITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SYS_C0024666
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SYS_C0024666" ON "AP_APPLICATIONS"."D_SERVERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SYS_C0024670
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SYS_C0024670" ON "AP_APPLICATIONS"."D_SOFTWARE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SYS_C0024673
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SYS_C0024673" ON "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SYS_C0024668
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SYS_C0024668" ON "AP_APPLICATIONS"."D_SOFTWARE_TYPES" ("SOFTWARE_TYPE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_USER_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_USER_ROLES_PK" ON "AP_APPLICATIONS"."D_USER_ROLES" ("USERNAME", "ROLE", "ENTITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_USER_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_USER_STATUS_PK" ON "AP_APPLICATIONS"."D_USER_STATUS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index D_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_USERS_PK" ON "AP_APPLICATIONS"."D_USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index MPC_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."MPC_LIST_PK" ON "AP_APPLICATIONS"."MPC_LIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index PS_TXN_IDX
--------------------------------------------------------

  CREATE INDEX "AP_APPLICATIONS"."PS_TXN_IDX" ON "AP_APPLICATIONS"."PS_TXN" ("COLLID", "ID") REVERSE 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SECRET_SANTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SECRET_SANTA_PK" ON "AP_APPLICATIONS"."SECRET_SANTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SECRET_SANTA_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SECRET_SANTA_UK1" ON "AP_APPLICATIONS"."SECRET_SANTA" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index SQL_VERSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."SQL_VERSION_PK" ON "AP_APPLICATIONS"."SQL_VERSION" ("OBJECT_NAME", "OBJECT_TYPE", "VERSION", "OWNER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Index T_MAILING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AP_APPLICATIONS"."T_MAILING_PK" ON "AP_APPLICATIONS"."T_MAILING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" ;
--------------------------------------------------------
--  DDL for Trigger D_ENTITIES_BIFER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AP_APPLICATIONS"."D_ENTITIES_BIFER" 
BEFORE INSERT ON D_ENTITIES 
FOR EACH ROW 
BEGIN
    IF INSERTING THEN
      SELECT TAG || LPAD(D_ENTITIES_SEQ01.NEXTVAL,7,'0') INTO :NEW.ID FROM D_ENTITY_TYPES WHERE TYPE = :NEW.TYPE;
    END IF;
END;
/
ALTER TRIGGER "AP_APPLICATIONS"."D_ENTITIES_BIFER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger D_USERS_TO_LOWERCASE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AP_APPLICATIONS"."D_USERS_TO_LOWERCASE" 
BEFORE INSERT OR UPDATE OF USERNAME ON D_USERS 
FOR EACH ROW 
BEGIN
   :NEW.USERNAME := LOWER(:NEW.USERNAME);
END;
/
ALTER TRIGGER "AP_APPLICATIONS"."D_USERS_TO_LOWERCASE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MPC_LIST_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AP_APPLICATIONS"."MPC_LIST_TRG" 
BEFORE INSERT ON MPC_LIST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    :new.id := MPC_LIST_SEQ.nextval;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AP_APPLICATIONS"."MPC_LIST_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SECRET_SANTA_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AP_APPLICATIONS"."SECRET_SANTA_TRG" 
BEFORE INSERT ON SECRET_SANTA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    :new.id := secret_santa_seq.nextval;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "AP_APPLICATIONS"."SECRET_SANTA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_MAILING_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AP_APPLICATIONS"."T_MAILING_TRG" 
BEFORE INSERT ON T_MAILING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT T_MAILING_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AP_APPLICATIONS"."T_MAILING_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table D_COMPANY_SETTINGS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_COMPANY_SETTINGS" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_COMPANY_SETTINGS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_COMPANY_SETTINGS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_COMPANY_SETTINGS" ADD CONSTRAINT "D_COMPANY_SETTINGS_PK" PRIMARY KEY ("COMPANY", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 166 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_ENTITIES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ENTITIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITIES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITIES" ADD CONSTRAINT "D_ENTITIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITIES" ADD CONSTRAINT "D_ENTITIES_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_ENTITY_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" MODIFY ("MODULE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" MODIFY ("PURPOSE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" ADD CONSTRAINT "D_ENTITY_ATTRIBUTES_PK" PRIMARY KEY ("ENTITY", "NAME", "MODULE", "PURPOSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_ENTITY_TYPES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_TYPES" MODIFY ("TAG" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_TYPES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_TYPES" ADD CONSTRAINT "D_ENTITY_TYPE_PK" PRIMARY KEY ("TYPE")
  USING INDEX (CREATE UNIQUE INDEX "AP_APPLICATIONS"."D_ENTITY_TYPE_PK1" ON "AP_APPLICATIONS"."D_ENTITY_TYPES" ("TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_ENVIRONMENTS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ENVIRONMENTS" ADD PRIMARY KEY ("ENVIRONMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_MAILING_LIST_USERS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_MAILING_LIST_USERS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table D_MAILING_LISTS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_MAILING_LISTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_MAILING_LISTS" ADD CONSTRAINT "D_MAILING_LISTS_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_ROLES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ROLES" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ROLES" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ROLES" MODIFY ("ROLE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_ROLES" ADD CONSTRAINT "D_ROLES_PK" PRIMARY KEY ("ROLE", "ENTITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_SERVERS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_SERVERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_SERVERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_SOFTWARE
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_SOFTWARE_DETAILS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_SOFTWARE_TYPES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE_TYPES" ADD PRIMARY KEY ("SOFTWARE_TYPE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_USER_ROLES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USER_ROLES" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USER_ROLES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USER_ROLES" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USER_ROLES" ADD CONSTRAINT "D_USER_ROLES_PK" PRIMARY KEY ("USERNAME", "ROLE", "ENTITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_USER_STATUS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_USER_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USER_STATUS" ADD CONSTRAINT "D_USER_STATUS_PK" PRIMARY KEY ("STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table D_USERS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_USERS" ADD CONSTRAINT "D_USERS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
  ALTER TABLE "AP_APPLICATIONS"."D_USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."D_USERS" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MPC_LIST
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."MPC_LIST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."MPC_LIST" ADD CONSTRAINT "MPC_LIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PS_TXN
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."PS_TXN" ADD CONSTRAINT "PS_TXN_PK" PRIMARY KEY ("COLLID", "ID")
  USING INDEX (CREATE INDEX "AP_APPLICATIONS"."PS_TXN_IDX" ON "AP_APPLICATIONS"."PS_TXN" ("COLLID", "ID") REVERSE 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECRET_SANTA
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."SECRET_SANTA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SECRET_SANTA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SECRET_SANTA" ADD CONSTRAINT "SECRET_SANTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
  ALTER TABLE "AP_APPLICATIONS"."SECRET_SANTA" ADD CONSTRAINT "SECRET_SANTA_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SQL_SUBPROGRAMS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."SQL_SUBPROGRAMS" MODIFY ("OBJECT_NAME_PARENT" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_SUBPROGRAMS" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_SUBPROGRAMS" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_SUBPROGRAMS" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_SUBPROGRAMS" MODIFY ("OBJECT_TYPE_PARENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SQL_VERSION
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."SQL_VERSION" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_VERSION" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_VERSION" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_VERSION" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_VERSION" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."SQL_VERSION" ADD CONSTRAINT "SQL_VERSION_PK" PRIMARY KEY ("OBJECT_NAME", "OBJECT_TYPE", "VERSION", "OWNER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_MAILING
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."T_MAILING" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."T_MAILING" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."T_MAILING" MODIFY ("SENT" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."T_MAILING" MODIFY ("NOT_BEFORE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."T_MAILING" MODIFY ("MAILING_LIST" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."T_MAILING" MODIFY ("MAIL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AP_APPLICATIONS"."T_MAILING" ADD CONSTRAINT "T_MAILING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_UTIL_APP"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_ENTITIES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ENTITIES" ADD CONSTRAINT "D_ENTITIES_FK1" FOREIGN KEY ("TYPE")
	  REFERENCES "AP_APPLICATIONS"."D_ENTITY_TYPES" ("TYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_ENTITY_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ENTITY_ATTRIBUTES" ADD CONSTRAINT "D_ENTITY_ATTRIBUTES_FK1" FOREIGN KEY ("ENTITY")
	  REFERENCES "AP_APPLICATIONS"."D_ENTITIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_MAILING_LIST_USERS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_MAILING_LIST_USERS" ADD CONSTRAINT "D_MAILING_LIST_USERS_FK1" FOREIGN KEY ("NAME")
	  REFERENCES "AP_APPLICATIONS"."D_MAILING_LISTS" ("NAME") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AP_APPLICATIONS"."D_MAILING_LIST_USERS" ADD CONSTRAINT "D_MAILING_LIST_USERS_FK2" FOREIGN KEY ("USERNAME")
	  REFERENCES "AP_APPLICATIONS"."D_USERS" ("USERNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_ROLES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_ROLES" ADD CONSTRAINT "D_ROLES_FK1" FOREIGN KEY ("ENTITY")
	  REFERENCES "AP_APPLICATIONS"."D_ENTITIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_SERVERS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_SERVERS" ADD CONSTRAINT "FK_ENVIRONMENT" FOREIGN KEY ("ENVIRONMENT")
	  REFERENCES "AP_APPLICATIONS"."D_ENVIRONMENTS" ("ENVIRONMENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_SOFTWARE
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE" ADD CONSTRAINT "FK_SOFTWARE_TYPE" FOREIGN KEY ("SOFTWARE_TYPE_NAME")
	  REFERENCES "AP_APPLICATIONS"."D_SOFTWARE_TYPES" ("SOFTWARE_TYPE_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_SOFTWARE_DETAILS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" ADD CONSTRAINT "FK_SOFTWARE" FOREIGN KEY ("SOFTWARE_ID")
	  REFERENCES "AP_APPLICATIONS"."D_SOFTWARE" ("ID") ENABLE;
  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" ADD CONSTRAINT "FK_SERVER" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "AP_APPLICATIONS"."D_SERVERS" ("ID") ENABLE;
  ALTER TABLE "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" ADD CONSTRAINT "FK_PARENT" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "AP_APPLICATIONS"."D_SOFTWARE_DETAILS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_USER_ROLES" ADD CONSTRAINT "D_USER_ROLES_FK2" FOREIGN KEY ("ROLE", "ENTITY")
	  REFERENCES "AP_APPLICATIONS"."D_ROLES" ("ROLE", "ENTITY") ENABLE;
  ALTER TABLE "AP_APPLICATIONS"."D_USER_ROLES" ADD CONSTRAINT "D_USER_ROLES_FK1" FOREIGN KEY ("STATUS")
	  REFERENCES "AP_APPLICATIONS"."D_USER_STATUS" ("STATUS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table D_USERS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."D_USERS" ADD CONSTRAINT "D_USERS_FK1" FOREIGN KEY ("STATUS")
	  REFERENCES "AP_APPLICATIONS"."D_USER_STATUS" ("STATUS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SQL_SUBPROGRAMS
--------------------------------------------------------

  ALTER TABLE "AP_APPLICATIONS"."SQL_SUBPROGRAMS" ADD CONSTRAINT "SQL_SUBPROGRAMS_FK1" FOREIGN KEY ("OBJECT_NAME_PARENT", "OBJECT_TYPE_PARENT", "VERSION", "OWNER")
	  REFERENCES "AP_APPLICATIONS"."SQL_VERSION" ("OBJECT_NAME", "OBJECT_TYPE", "VERSION", "OWNER") ENABLE;
